name: 'Test and lint'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ZIG_VERSION: 0.14.0-dev.1342+1a178d499

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev libsdl2-image-dev libwebp-dev
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      - name: Run tests
        run: zig build test
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install sdl2 sdl2_image sdl2_ttf harfbuzz graphite2
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}
      - name: Run tests
        run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      - run: zig fmt --check .
